Update: enable irsa for cert-manager
giantswarm/default-apps-aws pull request #170
Opened 2023-02-28 15:48 UTC by zewolfe

### What this PR does / why we need it

Towards - https://github.com/giantswarm/roadmap/issues/1981

### Checklist

- [ ] Update changelog in CHANGELOG.md.

2023-02-28 15:51 UTC, fiunchinho approved these changes

2023-02-28 17:26 UTC, fiunchinho commented
/test create
/test upgrade

2023-03-09 19:57 UTC, AndiDog approved these changes
LGTM since I tested together with https://github.com/giantswarm/capa-iam-operator/pull/164 and https://github.com/giantswarm/cert-manager-app/pull/295

2023-03-16 09:48 UTC, AndiDog requested changes
This is from cert-manager-app:

```
{{- define "giantswarm.serviceAccountAnnotations" -}}
{{- if and (eq .Values.provider "aws") (eq .Values.controller.aws.irsa "true") (not (hasKey .Values.controller.serviceAccount.annotations "eks.amazonaws.com/role-arn")) }}
{{- $_ := set .Values.controller.serviceAccount.annotations "eks.amazonaws.com/role-arn" (tpl "arn:aws:iam::{{ .Values.aws.accountID }}:role/{{ template \"aws.iam.role\" . }}" .) }}
{{- else if and (eq .Values.provider "capa") (not (hasKey .Values.controller.serviceAccount.annotations "eks.amazonaws.com/role-arn")) }}
{{- $_ := set .Values.controller.serviceAccount.annotations "eks.amazonaws.com/role-arn" (include "aws.iam.role" .) }}
{{- end }}
{{- end -}}
```

So `controller.aws.irsa` is only relevant for vintage, but our ticket only covers the CAPI product. I think we can therefore discard this PR? @zewolfe

2023-03-16 23:17 UTC, closed without merging